n, m = input().split()
n = int(n)
m = int(m)
s1 = set()
s2 = set()
ss = set()
for i in range(n):
    a = int(input())
    s1.add(a)
for i in range(m):
    b = int(input())
    s2.add(b)
ss = (s1 & s2)
print(len(ss))
print(*sorted(ss))
ss = (s1 - s2)
print(len(ss))
print(*sorted(ss))
ss = (s2 - s1)
print(len(ss))
print(*sorted(ss))  